### ISSUE TITLE
ccs command seems to be wrong

### ISSUE THREAD

**Issue by rkizen** [ben-lerch/IsoSeq-3.0#11]
The order of the input and output seem to be flipped in the ccs command example:
 ccs --noPolish --minLength=300 --minPasses=1 --minZScore=-999 --maxDropFraction=0.8 --minPredictedAccuracy=0.8 --minSnr=4 ccs.bam subreads.bam

Should be:
 ccs --noPolish --minLength=300 --minPasses=1 --minZScore=-999 --maxDropFraction=0.8 --minPredictedAccuracy=0.8 --minSnr=4 subreads.bam ccs.bam

**Comment by ylipacbio** [comment]
Thanks rkizen!
