### ISSUE TITLE
SMRT analysis 2.2 versus SMRT analysis 3.0

### ISSUE THREAD

**Issue by sjin09** [ben-lerch/IsoSeq-3.0#13]
To whom it may concern,

I am writing to inquire about the usability of SMRT analysis 3.0 for Isoseq analysis.  The ISoseq have been sequenced with P6C4 on RSII. I have followed the documentation (https://github.com/ben-lerch/IsoSeq-3.0) for processing the Isoseq. In addition, I have previously performed the same pipeline (ccs, classify, cluster) with SMRT analysis 2.2.

I have noticed that there has been a change in the consensus algorithm from QUIVER to ARROW, which I much appreciated based on the improvements in the Quality score. After performing QUIVER with SMRT analysis 2.2, there were hq.fasta and lq.fasta as outputs. On the other hand in SMRT analysis 3.0 the consensus output is the /output/final.consensus.fasta only. The number of high quality transcripts between the two processes seems to have changed a lot. Based on these observations I had some questions:

1. Do you recommend using SMRT analysis 3.0 over SMRT analysis 2.2?
2. If not when would you recommend to use SMRT analysis 3.0?
2. In addition, I was wondering if not having the hq.fasta and lq.fasta is the default for SMRT analysis 3.0 and ARROW.

**Comment by Magdoll** [comment]
Hi,

First sorry for the late response.

SMRTAnalysis 3.0 did not include Quiver in the Iso-Seq analysis, hence there were only "consensus" (DAGCon) outputs and no HQ vs LQ. In that sense it is inferior to 2.2.

Quiver was added to Iso-Seq in SMRTAnalysis 3.2 and later (see here: https://github.com/Magdoll/IsoSeq_SA3nUP/wiki). I believe SA3.2 is not released through SMRTAnalysis yet, but using the wiki you can see that it can be installed using pitchfork, which is some amount of work.

For this purpose, we would recommend 2.2 over 3.0. Unless you want to wait for later SA3.2+ releases or go for pitchfork installation of SA3.2.

**Comment by sjin09** [comment]
Cheers for the answer!

I noticed a poor alignment statistics with the final consensus sequences from SMRTAnalysis 3.0. I also noticed large discrepancies in the alignment statistics between hq and lq fasta from SMRTAnalysis 2.2. I have been using hq fasta from there on for further analysis. 

I am excited for the future developments of Isoseq.
