### ISSUE TITLE
Does the iso-seq protocol use Quiver rather than arrow for polish?

### ISSUE THREAD

**Issue by RobinQi** [ben-lerch/IsoSeq-3.0#9]
Hi ben lerch,
I saw that in the cluster step, the command of pbtranscript cluster still use quiver rather than arrow. I want to know why arrow algorithm is not used in this protocol?
Thanks.

**Comment by ylipacbio** [comment]
The latest git master repo should be using the ‘variantCaller --algorithm=best’ to call consensus (which means Arrow will be used on sequel data and Quiver on RS data).

We still use the term ‘quiver’ to refer to ‘consensus calling’ in coding, which needs to be replaced later.

**Comment by RobinQi** [comment]
OK, Thanks.
